In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
veriler = pd.read_csv("veriler.csv")

In [3]:
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [4]:
eksikVeriler = pd.read_csv("eksikveriler.csv")

In [5]:
eksikVeriler

ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [6]:
imputer = SimpleImputer(missing_values=np.nan , strategy="mean") # Eksik Sayısal verileri ortalama ile doldurma işlemi yapılacak

In [7]:
yas = eksikVeriler.iloc[:,1:4].values

In [8]:
yas

array([[130.,  30.,  10.],
       [125.,  36.,  11.],
       [135.,  34.,  10.],
       [133.,  30.,   9.],
       [129.,  38.,  12.],
       [180.,  90.,  30.],
       [190.,  80.,  25.],
       [175.,  90.,  35.],
       [177.,  60.,  22.],
       [185., 105.,  33.],
       [165.,  55.,  27.],
       [155.,  50.,  44.],
       [160.,  58.,  nan],
       [162.,  59.,  41.],
       [167.,  62.,  55.],
       [174.,  70.,  47.],
       [193.,  90.,  nan],
       [187.,  80.,  27.],
       [183.,  88.,  28.],
       [159.,  40.,  29.],
       [164.,  66.,  32.],
       [166.,  56.,  42.]])

In [9]:
imputer = imputer.fit(yas[:,1:4])

In [10]:
yas[:,1:4] = imputer.transform(yas[:,1:4])

In [11]:
yas

array([[130.  ,  30.  ,  10.  ],
       [125.  ,  36.  ,  11.  ],
       [135.  ,  34.  ,  10.  ],
       [133.  ,  30.  ,   9.  ],
       [129.  ,  38.  ,  12.  ],
       [180.  ,  90.  ,  30.  ],
       [190.  ,  80.  ,  25.  ],
       [175.  ,  90.  ,  35.  ],
       [177.  ,  60.  ,  22.  ],
       [185.  , 105.  ,  33.  ],
       [165.  ,  55.  ,  27.  ],
       [155.  ,  50.  ,  44.  ],
       [160.  ,  58.  ,  28.45],
       [162.  ,  59.  ,  41.  ],
       [167.  ,  62.  ,  55.  ],
       [174.  ,  70.  ,  47.  ],
       [193.  ,  90.  ,  28.45],
       [187.  ,  80.  ,  27.  ],
       [183.  ,  88.  ,  28.  ],
       [159.  ,  40.  ,  29.  ],
       [164.  ,  66.  ,  32.  ],
       [166.  ,  56.  ,  42.  ]])

In [12]:
ulke = veriler.iloc[:,0:1]

In [13]:
ulke

ulke
0    tr
1    tr
2    tr
3    tr
4    tr
5    tr
6    tr
7    tr
8    tr
9    us
10   us
11   us
12   us
13   us
14   us
15   fr
16   fr
17   fr
18   fr
19   fr
20   fr
21   fr

In [14]:
le = preprocessing.LabelEncoder()

In [15]:
ulke = le.fit_transform(veriler.iloc[:,0])

In [16]:
 ulke = ulke.reshape(-1, 1)

In [17]:
ohe = preprocessing.OneHotEncoder()

In [18]:
ulke = ohe.fit_transform(ulke).toarray() #Bu kısımdaki işlem sayesinde kategorik veriler sayısal verilere dönüştürüldü.

In [19]:
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [20]:
sonuc = pd.DataFrame(data=ulke , index=range(22),columns=["fr" , "tr","us"])

In [21]:
sonuc

fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [22]:
sonuc2 =pd.DataFrame(data=yas,index=range(22),columns=["boy","kilo","yas"])

In [23]:
sonuc2

boy   kilo    yas
0   130.0   30.0  10.00
1   125.0   36.0  11.00
2   135.0   34.0  10.00
3   133.0   30.0   9.00
4   129.0   38.0  12.00
5   180.0   90.0  30.00
6   190.0   80.0  25.00
7   175.0   90.0  35.00
8   177.0   60.0  22.00
9   185.0  105.0  33.00
10  165.0   55.0  27.00
11  155.0   50.0  44.00
12  160.0   58.0  28.45
13  162.0   59.0  41.00
14  167.0   62.0  55.00
15  174.0   70.0  47.00
16  193.0   90.0  28.45
17  187.0   80.0  27.00
18  183.0   88.0  28.00
19  159.0   40.0  29.00
20  164.0   66.0  32.00
21  166.0   56.0  42.00

In [24]:
cinsiyet = veriler.iloc[:,-1].values

In [25]:
cinsiyet

array(['e', 'e', 'k', 'k', 'e', 'e', 'e', 'e', 'k', 'e', 'k', 'k', 'k',
       'k', 'k', 'e', 'e', 'e', 'e', 'k', 'k', 'k'], dtype=object)

In [26]:
sonuc3 = pd.DataFrame(data=cinsiyet,index=range(22),columns=["cinsiyet"])

In [27]:
sonuc3

cinsiyet
0         e
1         e
2         k
3         k
4         e
5         e
6         e
7         e
8         k
9         e
10        k
11        k
12        k
13        k
14        k
15        e
16        e
17        e
18        e
19        k
20        k
21        k

In [28]:
s = pd.concat([sonuc,sonuc2],axis=1) # Bu yapılan işlem sayesinde kolon olarak birleştirme işlemi yapıldı

In [29]:
s

fr   tr   us    boy   kilo    yas
0   0.0  1.0  0.0  130.0   30.0  10.00
1   0.0  1.0  0.0  125.0   36.0  11.00
2   0.0  1.0  0.0  135.0   34.0  10.00
3   0.0  1.0  0.0  133.0   30.0   9.00
4   0.0  1.0  0.0  129.0   38.0  12.00
5   0.0  1.0  0.0  180.0   90.0  30.00
6   0.0  1.0  0.0  190.0   80.0  25.00
7   0.0  1.0  0.0  175.0   90.0  35.00
8   0.0  1.0  0.0  177.0   60.0  22.00
9   0.0  0.0  1.0  185.0  105.0  33.00
10  0.0  0.0  1.0  165.0   55.0  27.00
11  0.0  0.0  1.0  155.0   50.0  44.00
12  0.0  0.0  1.0  160.0   58.0  28.45
13  0.0  0.0  1.0  162.0   59.0  41.00
14  0.0  0.0  1.0  167.0   62.0  55.00
15  1.0  0.0  0.0  174.0   70.0  47.00
16  1.0  0.0  0.0  193.0   90.0  28.45
17  1.0  0.0  0.0  187.0   80.0  27.00
18  1.0  0.0  0.0  183.0   88.0  28.00
19  1.0  0.0  0.0  159.0   40.0  29.00
20  1.0  0.0  0.0  164.0   66.0  32.00
21  1.0  0.0  0.0  166.0   56.0  42.00

In [30]:
s2 = pd.concat([s,sonuc3],axis=1)

In [31]:
s2

fr   tr   us    boy   kilo    yas cinsiyet
0   0.0  1.0  0.0  130.0   30.0  10.00        e
1   0.0  1.0  0.0  125.0   36.0  11.00        e
2   0.0  1.0  0.0  135.0   34.0  10.00        k
3   0.0  1.0  0.0  133.0   30.0   9.00        k
4   0.0  1.0  0.0  129.0   38.0  12.00        e
5   0.0  1.0  0.0  180.0   90.0  30.00        e
6   0.0  1.0  0.0  190.0   80.0  25.00        e
7   0.0  1.0  0.0  175.0   90.0  35.00        e
8   0.0  1.0  0.0  177.0   60.0  22.00        k
9   0.0  0.0  1.0  185.0  105.0  33.00        e
10  0.0  0.0  1.0  165.0   55.0  27.00        k
11  0.0  0.0  1.0  155.0   50.0  44.00        k
12  0.0  0.0  1.0  160.0   58.0  28.45        k
13  0.0  0.0  1.0  162.0   59.0  41.00        k
14  0.0  0.0  1.0  167.0   62.0  55.00        k
15  1.0  0.0  0.0  174.0   70.0  47.00        e
16  1.0  0.0  0.0  193.0   90.0  28.45        e
17  1.0  0.0  0.0  187.0   80.0  27.00        e
18  1.0  0.0  0.0  183.0   88.0  28.00        e
19  1.0  0.0  0.0  159.0   40.0  29.00        k
20  1.0  0.0  0.0  164.0   66.0  32.00        k
21  1.0  0.0  0.0  166.0   56.0  42.00        k

In [33]:
x_train ,x_test ,y_train ,y_test =train_test_split(s,sonuc3,test_size=0.33,random_state=0)

In [35]:
sc = StandardScaler()

In [36]:
X_train = sc.fit_transform(x_train) # Bu işlem sayesinde veriler belli bir aralığa sıkıştırılmış oldu.

In [37]:
X_test = sc.fit_transform(x_test)

In [38]:
X_train

array([[-0.63245553,  0.8660254 , -0.40824829,  0.45049444, -0.29657884,
        -0.24717129],
       [-0.63245553,  0.8660254 , -0.40824829,  1.00824945,  0.5096549 ,
         0.03416189],
       [ 1.58113883, -1.15470054, -0.40824829,  1.13696215,  0.91277178,
         0.35769504],
       [-0.63245553,  0.8660254 , -0.40824829, -1.6089087 , -1.18343596,
        -1.18494855],
       [-0.63245553,  0.8660254 , -0.40824829, -1.35148331, -1.34468271,
        -1.372504  ],
       [-0.63245553,  0.8660254 , -0.40824829,  0.57920713,  0.91277178,
         0.50305051],
       [ 1.58113883, -1.15470054, -0.40824829,  0.87953676,  0.5096549 ,
         0.22171734],
       [-0.63245553, -1.15470054,  2.44948974,  0.79372829,  1.51744708,
         0.78438369],
       [-0.63245553,  0.8660254 , -0.40824829,  0.36468597,  0.91277178,
         0.97193914],
       [ 1.58113883, -1.15470054, -0.40824829,  0.70791983,  0.8321484 ,
         0.31549506],
       [-0.63245553,  0.8660254 , -0.40824829, -1.