In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np 
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix

In [2]:
veriler = pd.read_csv("Churn_Modelling.csv")
veriler

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
x = veriler.iloc[:,3:13].values
y = veriler.iloc[:,13].values

In [4]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [26]:
#Kategorik verileri numeric hale getirme işlemi
le1 = preprocessing.LabelEncoder()
x[:,1] = le1.fit_transform(x[:,1])

le2 = preprocessing.LabelEncoder()
x[:,2] = le2.fit_transform(x[:,2])
x[:,1].size

10000

In [27]:
#Ülke değerleri için bir sıralama işlemi yapılmaması için farklı kolonlara koyma işlemi yapılcak
ohe = ColumnTransformer([("ohe" , OneHotEncoder(dtype=float),[1])],remainder="passthrough")
x = ohe.fit_transform(x)
x = x[:,1:]
x[:,1].size

10000

In [8]:
#Eğitim ve test verilerine ayırma işlemi ...
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.33,random_state=0)

In [28]:
#Verileri standardize etme işlemi . 
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)
X_train[:,1].size

6700

In [41]:
#Yapay sinir ağı ...
##************************HATA VAR ***************************************##
# siniflandirma = Sequential()
# siniflandirma(Dense(units="6",kernel_initializer="uniform", activation="relu",input_dim = 11)) #Giriş katmanı 11 ara katman ise 6 nörondan oluşuyor.
# siniflandirma(Dense(units="6",kernel_initializer="uniform", activation="relu")) #Bir başka ara katman
# siniflandirma(Dense(units="1",kernel_initializer="uniform", activation="sigmoid"))#Çıkış katmanı
# siniflandirma.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
# siniflandirma.fit(x=X_train,y=y_train,epochs=50,verbose=1)

In [48]:
model = Sequential()
model.add(Dense(units="30",activation="relu"))
model.add(Dense(units="15",activation="relu"))
model.add(Dense(units="15",activation="relu"))
model.add(Dense(units="1",activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer = "adam",metrics=["accuracy"])
model.fit(x=X_train,y=y_train,epochs=70,verbose= 1,batch_size=1)#Burada verinin bölünmesinin önüne geçmek için batch_size=1 verildi

Epoch 1/70
6700/6700 [==============================] - 7s 931us/step - loss: 0.4050 - accuracy: 0.8272
Epoch 2/70
6700/6700 [==============================] - 6s 945us/step - loss: 0.3548 - accuracy: 0.8536
Epoch 3/70
6700/6700 [==============================] - 6s 942us/step - loss: 0.3497 - accuracy: 0.8554
Epoch 4/70
6700/6700 [==============================] - 6s 950us/step - loss: 0.3429 - accuracy: 0.8593
Epoch 5/70
6700/6700 [==============================] - 6s 957us/step - loss: 0.3412 - accuracy: 0.8628
Epoch 6/70
6700/6700 [==============================] - 6s 921us/step - loss: 0.3378 - accuracy: 0.8622
Epoch 7/70
6700/6700 [==============================] - 6s 920us/step - loss: 0.3357 - accuracy: 0.8601
Epoch 8/70
6700/6700 [==============================] - 6s 943us/step - loss: 0.3336 - accuracy: 0.8630
Epoch 9/70
6700/6700 [==============================] - 6s 953us/step - loss: 0.3326 - accuracy: 0.8642
Epoch 10/70
6700/6700 [==============================] - 6s 952u

In [49]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5 ) + 0

cm = confusion_matrix(y_test,y_pred)
# y_test
cm

104/104 [==============================] - 0s 736us/step


array([[2441,  176],
       [ 345,  338]], dtype=int64)

In [39]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [12]:
y_pred

array([[1, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 1]])