In [19]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [20]:
veriler = pd.read_csv("veriler.csv")

In [21]:
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [22]:
x = veriler.iloc[:,1:4].values
y = veriler.iloc[:,4:].values

In [23]:
x

array([[130,  30,  10],
       [125,  36,  11],
       [135,  34,  10],
       [133,  30,   9],
       [129,  38,  12],
       [180,  90,  30],
       [190,  80,  25],
       [175,  90,  35],
       [177,  60,  22],
       [185, 105,  33],
       [165,  55,  27],
       [155,  50,  44],
       [160,  58,  39],
       [162,  59,  41],
       [167,  62,  55],
       [174,  70,  47],
       [193,  90,  23],
       [187,  80,  27],
       [183,  88,  28],
       [159,  40,  29],
       [164,  66,  32],
       [166,  56,  42]], dtype=int64)

In [24]:
y

array([['e'],
       ['e'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [25]:
#Veri bölme işlemi
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.33,random_state=0)

In [26]:
x_train

array([[177,  60,  22],
       [190,  80,  25],
       [193,  90,  23],
       [129,  38,  12],
       [135,  34,  10],
       [180,  90,  30],
       [187,  80,  27],
       [185, 105,  33],
       [175,  90,  35],
       [183,  88,  28],
       [133,  30,   9],
       [130,  30,  10],
       [174,  70,  47],
       [160,  58,  39]], dtype=int64)

In [27]:
#Verileri bir standart altına alınması işlemi.
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [28]:
X_train

array([[ 0.45049444, -0.29657884, -0.26680787],
       [ 1.00824945,  0.5096549 ,  0.        ],
       [ 1.13696215,  0.91277178, -0.17787191],
       [-1.6089087 , -1.18343596, -1.15616745],
       [-1.35148331, -1.34468271, -1.33403936],
       [ 0.57920713,  0.91277178,  0.44467979],
       [ 0.87953676,  0.5096549 ,  0.17787191],
       [ 0.79372829,  1.51744708,  0.71148766],
       [ 0.36468597,  0.91277178,  0.88935957],
       [ 0.70791983,  0.8321484 ,  0.26680787],
       [-1.43729177, -1.50592946, -1.42297532],
       [-1.56600447, -1.50592946, -1.33403936],
       [ 0.32178174,  0.10653803,  1.95659106],
       [-0.27887751, -0.37720222,  1.2451034 ]])

In [29]:
#KNN algoritmasının kullanımı
knn = KNeighborsClassifier(n_neighbors=1,metric="minkowski")#Bakilacak komşu sayısı "n_neighbors" belirler.
knn.fit(X_train,y_train)

C:\Users\emirh\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1)

In [30]:
y_pred_knn = knn.predict(X_test)

In [31]:
y_test

array([['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [32]:
y_pred_knn

array(['k', 'k', 'e', 'k', 'e', 'k', 'k', 'k'], dtype=object)

In [33]:
#Verinin başarı oranı
cm = confusion_matrix(y_test,y_pred_knn)
cm

array([[1, 0],
       [1, 6]], dtype=int64)